const PHONE='918400050000';
const products=[
 {id:'teak-platform-bed',name:'The Teak Platform Bed',category:'bedroom',type:'Bed',desc:'A calm, grounded bed designed around the beauty of teak. Choose dimensions, headboard details and finish with our workshop.',image:'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1000&q=80',tag:'Made to order'},
 {id:'tailored-sofa',name:'The Tailored Sofa',category:'living',type:'Sofa',desc:'An inviting sofa with a crafted wooden frame. Discuss seating layout, upholstery and finish to suit your living room.',image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1000&q=80',tag:'Customisable'},
 {id:'dining-table',name:'The Gathering Table',category:'dining',type:'Dining table',desc:'A dining table made for everyday rituals and long conversations. Configure size, profile and seating.',image:'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1000&q=80',tag:'Made to order'},
 {id:'sofa-cum-bed',name:'The Convertible Sofa',category:'living',type:'Sofa-cum-bed',desc:'A thoughtful two-in-one piece for flexible rooms. Ask our team about mechanisms, dimensions and fabrics.',image:'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8c?w=1000&q=80',tag:'Space smart'},
 {id:'accent-chair',name:'The Accent Chair',category:'accent',type:'Chair',desc:'A comfortable chair with a distinctive wooden character. Available for tailored finishes and upholstery discussion.',image:'https://images.unsplash.com/photo-1503602642458-232111445657?w=1000&q=80',tag:'Customisable'},
 {id:'centre-table',name:'The Centre Table',category:'accent',type:'Centre table',desc:'A considered centrepiece for the living room, with a form and finish that can be made your own.',image:'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=1000&q=80',tag:'Made to order'},
 {id:'divan-cum-bed',name:'The Versatile Divan',category:'bedroom',type:'Divan-cum-bed',desc:'A flexible divan for lounging or hosting. Share your space and preferences for a tailored design.',image:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1000&q=80',tag:'Space smart'},
 {id:'dressing-table',name:'The Dressing Table',category:'bedroom',type:'Dressing table',desc:'Storage and a beautiful daily ritual in one handcrafted piece. Configure mirror, drawers and dimensions.',image:'https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=1000&q=80',tag:'Customisable'},
 {id:'bedroom-chair',name:'The Bedroom Chair',category:'bedroom',type:'Bedroom chair',desc:'A quiet corner companion, made with a teak frame and upholstery chosen for your room.',image:'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=1000&q=80',tag:'Made to order'}
];
const grid=document.querySelector('#product-grid');let filter='all';let cart=JSON.parse(localStorage.getItem('ssf-bag')||'[]');
function track(event,detail={}){window.dataLayer?.push({event,...detail});window.dispatchEvent(new CustomEvent('ssf:analytics',{detail:{event,...detail}}));}
function wa(text){track('whatsapp_click',{context:text.slice(0,40)});window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`,'_blank','noopener');}
function renderProducts(){const items=products.filter(p=>filter==='all'||p.category===filter);grid.innerHTML=items.map(p=>`<article class="product-card" data-id="${p.id}" tabindex="0" role="button" aria-label="View ${p.name}"><div class="product-image"><img src="${p.image}" alt="Illustrative ${p.type.toLowerCase()} interior photograph" loading="lazy" referrerpolicy="no-referrer"><span class="tag">${p.tag}</span></div><div class="product-info"><div><h3>${p.name}</h3><p>Custom quote · ${p.type}</p></div><button aria-label="View ${p.name}">↗</button></div></article>`).join('');grid.querySelectorAll('.product-card').forEach(card=>{card.addEventListener('click',()=>showProduct(card.dataset.id));card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showProduct(card.dataset.id)}})});}
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{filter=btn.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===btn));renderProducts();track('catalog_filter',{category:filter})}));
function persist(){localStorage.setItem('ssf-bag',JSON.stringify(cart));document.querySelector('#cart-count').textContent=cart.length;renderCart();}
function renderCart(){document.querySelector('#cart-items').innerHTML=cart.length?cart.map(id=>{const p=products.find(x=>x.id===id);return `<div class="cart-item"><div><strong>${p.name}</strong><small>Custom quote required</small></div><button data-remove="${id}" aria-label="Remove ${p.name}">Remove</button></div>`}).join(''):'<p class="empty">Your inquiry bag is empty. Add pieces from the collection to ask about them together.</p>';document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{cart=cart.filter(x=>x!==b.dataset.remove);persist();track('remove_from_bag',{product_id:b.dataset.remove})}));}
const overlay=document.querySelector('#overlay'),drawer=document.querySelector('#cart-drawer'),modal=document.querySelector('#product-modal'),info=document.querySelector('#info-modal');let previousFocus=null;
function closeAll(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');modal.hidden=true;info.hidden=true;overlay.hidden=true;document.body.style.overflow='';if(previousFocus)previousFocus.focus();}
function openPanel(which){previousFocus=document.activeElement;closeAll();overlay.hidden=false;document.body.style.overflow='hidden';if(which==='cart'){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');drawer.querySelector('[data-close]').focus();track('bag_view')}else{which.hidden=false;which.querySelector('[data-close]').focus();}}
function showProduct(id){const p=products.find(x=>x.id===id);if(!p)return;document.querySelector('#modal-content').innerHTML=`<div class="modal-layout"><div class="modal-image"><img src="${p.image}" alt="Illustrative ${p.type.toLowerCase()} interior photograph"></div><div class="modal-copy"><span class="eyebrow">${p.category.toUpperCase()} · CUSTOM MADE</span><h2 id="modal-title">${p.name}</h2><p>${p.desc}</p><ul><li>Discuss solid teak construction and finishing</li><li>Dimensions and details tailored to your brief</li><li>5-year furniture guarantee; terms confirmed at purchase</li></ul><p><strong>Pricing:</strong> quoted after design and size are agreed.</p><div class="modal-actions"><button class="button dark" id="add-bag">Add to inquiry bag <span>+</span></button><button class="button" id="ask-product">Ask on WhatsApp <span>↗</span></button></div></div></div>`;document.querySelector('#add-bag').onclick=()=>{if(!cart.includes(id))cart.push(id);persist();track('add_to_bag',{product_id:id});openPanel('cart')};document.querySelector('#ask-product').onclick=()=>wa(`Hello, I'm interested in ${p.name}. Could you share options and a quote?`);history.replaceState(null,'',`#product/${id}`);openPanel(modal);track('product_view',{product_id:id});}
document.querySelector('#cart-open').onclick=()=>openPanel('cart');document.querySelector('#cart-inquire').onclick=()=>{if(cart.length)wa(`Hello, I'd like a quote for these pieces: ${cart.map(id=>products.find(p=>p.id===id)?.name).join(', ')}. Please contact me about customisation and availability.`);else document.querySelector('#cart-items').focus()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeAll);overlay.onclick=closeAll;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});
document.querySelector('#custom-form').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));const msg=`Hello, I'd like to discuss custom furniture.\nName: ${d.name}\nPhone: ${d.phone}\nPiece: ${d.type}\nApproximate size: ${d.size||'To discuss'}\nFinish: ${d.finish}\nNotes: ${d.notes||'To discuss'}`;track('custom_inquiry_submit',{type:d.type});wa(msg)});
document.querySelector('#floating-wa').onclick=()=>wa("Hello, I'd like to learn more about your custom furniture.");
const information={privacy:{title:'Privacy',body:'This website stores only your inquiry bag on your own device. Custom-order form details are passed to WhatsApp only when you choose to send an inquiry. We do not store your form details or payment information on this website. If analytics is added later, this notice should be updated before activation.'},terms:{title:'Terms & guarantee',body:'Furniture purchases are described as having a 5-year guarantee. Exact coverage, exclusions, care instructions and claim process should be confirmed in written order terms before payment. Product imagery is illustrative and every custom specification and final price requires showroom confirmation. This website does not currently accept online payment.'},delivery:{title:'Delivery & installation',body:'Delivery areas, charges, timelines, installation responsibilities and returns depend on each order and should be confirmed by the showroom in writing before you place an order.'}};
document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>{const item=information[b.dataset.info];document.querySelector('#info-content').innerHTML=`<span class="eyebrow">INFORMATION</span><h2 id="info-title">${item.title}</h2><p>${item.body}</p>`;openPanel(info)});
document.querySelector('#menu-btn').onclick=e=>{const nav=document.querySelector('.site-header nav');const open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))};document.querySelectorAll('.site-header nav a').forEach(a=>a.onclick=()=>{document.querySelector('.site-header nav').classList.remove('open');document.querySelector('#menu-btn').setAttribute('aria-expanded','false')});
document.querySelector('#year').textContent=new Date().getFullYear();renderProducts();persist();if(location.hash.startsWith('#product/'))showProduct(location.hash.slice(9));
