const PHONE='918400050000';
const products=[
  {id:'atelier-sofa',name:'The Atelier Sofa',category:'living',kind:'sofa',detail:'An inviting teak-framed sofa, ready to be shaped around your room, fabric and preferred seat feel.',image:'assets/sofa-editorial.jpg',label:'A place to pause'},
  {id:'quiet-bed',name:'The Quiet Bed',category:'bedroom',kind:'bed',detail:'A composed teak bed with a presence that feels grounded. Discuss size, headboard and finishing.',image:'assets/bed-editorial.jpg',label:'A room to return to'},
  {id:'gathering-table',name:'The Gathering Table',category:'dining',kind:'dining',detail:'A dining table to bring people together. Set the size, silhouette and wood detailing to suit your space.',image:'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1100&q=82',label:'Room for everyone'},
  {id:'everyday-divan',name:'The Everyday Divan',category:'bedroom',kind:'divan',detail:'A flexible divan-cum-bed for sitting, resting and welcoming guests. Plan its proportions and storage with us.',image:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1100&q=82',label:'Space, reimagined'},
  {id:'corner-chair',name:'The Corner Chair',category:'accents',kind:'chair',detail:'A small statement for a quiet corner, with woodwork and upholstery selected around your home.',image:'https://images.unsplash.com/photo-1503602642458-232111445657?w=1100&q=82',label:'A little character'},
  {id:'centre-piece',name:'The Centre Piece',category:'accents',kind:'centre',detail:'A centre table with a form that can be tailored to your living room and daily rituals.',image:'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=1100&q=82',label:'The room’s anchor'}
];
const types={sofa:{name:'Sofa',sizes:['2 seater','3 seater','L-shape','Custom size'],fabric:true,comfort:true,image:'assets/sofa-editorial.jpg'},bed:{name:'Bed',sizes:['Queen','King','Custom size'],fabric:false,comfort:false,image:'assets/bed-editorial.jpg'},divan:{name:'Divan-cum-bed',sizes:['Single','Double','Custom size'],fabric:true,comfort:true,image:'assets/bed-editorial.jpg'},dining:{name:'Dining table',sizes:['4 seater','6 seater','8 seater','Custom size'],fabric:false,comfort:false,image:'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1100&q=82'},chair:{name:'Chair',sizes:['Accent chair','Bedroom chair','Custom size'],fabric:true,comfort:true,image:'https://images.unsplash.com/photo-1503602642458-232111445657?w=1100&q=82'},centre:{name:'Centre table',sizes:['Compact','Standard','Custom size'],fabric:false,comfort:false,image:'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=1100&q=82'}};
const fabrics=[{name:'Oxblood',color:'#652c2c'},{name:'Sand',color:'#c6b8a1'},{name:'Olive',color:'#666952'},{name:'Charcoal',color:'#4b4b4b'},{name:'Bring my own',color:'linear-gradient(135deg,#d2c9ba 50%,#655b50 50%)'}];
const finishes=[{name:'Natural teak',color:'#a46a3e'},{name:'Deep teak',color:'#68432e'},{name:'Honey teak',color:'#bd8954'}];
const woodwork=['Clean lines','Soft curves','Carved detail','Let’s discuss'];
const comfort=['Balanced','Plush','Supportive'];
let filter='all',selectedProduct=null,lastFocus=null;
let bag=readBag();
let studio={mode:'new',type:'sofa',productId:null,size:'3 seater',fabric:'Oxblood',finish:'Natural teak',woodwork:'Clean lines',comfort:'Balanced'};
function readBag(){try{const value=JSON.parse(localStorage.getItem('ssf-bag-v2')||'[]');return Array.isArray(value)?value:[]}catch{return []}}
function saveBag(){localStorage.setItem('ssf-bag-v2',JSON.stringify(bag));document.querySelector('#bag-count').textContent=bag.length;renderBag()}
function analytics(event,detail={}){window.dataLayer?.push({event,...detail});window.dispatchEvent(new CustomEvent('ssf:analytics',{detail:{event,...detail}}))}
function whatsapp(message){analytics('whatsapp_click');window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(message)}`,'_blank','noopener')}
function renderProducts(){const shown=products.filter(p=>filter==='all'||p.category===filter);document.querySelector('#product-grid').innerHTML=shown.map((p,i)=>`<article class="product-card reveal"><div class="product-photo" role="button" tabindex="0" data-view="${p.id}" aria-label="View ${p.name}"><img src="${p.image}" alt="Illustrative ${p.name.toLowerCase()} reference" loading="lazy"><span class="product-no">${String(i+1).padStart(2,'0')} / ${p.label.toUpperCase()}</span></div><div class="product-meta"><div><h3 class="product-title">${p.name}</h3><small>Made to order · Quote on request</small></div><div class="product-actions"><button data-view="${p.id}" aria-label="View ${p.name}">View</button><button data-customize="${p.id}" aria-label="Customize ${p.name}">Customise ↗</button></div></div></article>`).join('');document.querySelectorAll('[data-view]').forEach(el=>{el.addEventListener('click',()=>openProduct(el.dataset.view));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProduct(el.dataset.view)}})});document.querySelectorAll('[data-customize]').forEach(el=>el.addEventListener('click',()=>openStudio('existing',el.dataset.customize)));observeReveals()}
document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('click',()=>{filter=el.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===el));renderProducts();analytics('catalog_filter',{category:filter})}));
const overlay=document.querySelector('#overlay'),bagPanel=document.querySelector('#bag'),productDialog=document.querySelector('#product-dialog'),studioDialog=document.querySelector('#studio-dialog'),infoDialog=document.querySelector('#info-dialog');
function closePanels(){bagPanel.classList.remove('open');bagPanel.setAttribute('aria-hidden','true');productDialog.hidden=true;studioDialog.hidden=true;infoDialog.hidden=true;overlay.hidden=true;document.body.classList.remove('no-scroll');if(lastFocus?.isConnected)lastFocus.focus()}
function openPanel(panel){lastFocus=document.activeElement;bagPanel.classList.remove('open');bagPanel.setAttribute('aria-hidden','true');productDialog.hidden=true;studioDialog.hidden=true;infoDialog.hidden=true;overlay.hidden=false;document.body.classList.add('no-scroll');if(panel===bagPanel){panel.classList.add('open');panel.setAttribute('aria-hidden','false')}else panel.hidden=false;panel.querySelector('.close')?.focus()}
document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closePanels));overlay.addEventListener('click',closePanels);document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanels()});
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;selectedProduct=p;document.querySelector('#product-dialog-content').innerHTML=`<div class="product-layout"><img src="${p.image}" alt="Illustrative ${p.name.toLowerCase()} reference"><div class="product-copy"><span class="kicker">A STARTING POINT · ${p.category.toUpperCase()}</span><h2 id="product-title">${p.name}</h2><p>${p.detail}</p><ul><li>Made in our workshop with teak at its heart</li><li>Discuss proportions, woodwork and finishing</li><li>Five-year furniture guarantee; terms confirmed at purchase</li></ul><p>Final details and price are quoted after your brief is reviewed.</p><div class="product-buttons"><button class="button dark" id="product-customize">Customise this piece <span>↗</span></button><button class="button secondary" id="product-bag">Add to inquiry bag <span>+</span></button></div></div></div>`;document.querySelector('#product-customize').onclick=()=>openStudio('existing',p.id);document.querySelector('#product-bag').onclick=()=>{if(!bag.includes(p.id))bag.push(p.id);saveBag();openPanel(bagPanel);analytics('add_to_bag',{product_id:p.id})};openPanel(productDialog);analytics('product_view',{product_id:p.id})}
document.querySelector('#bag-trigger').onclick=()=>openPanel(bagPanel);
function renderBag(){document.querySelector('#bag-items').innerHTML=bag.length?bag.map(id=>{const p=products.find(x=>x.id===id);return p?`<div class="bag-item"><div><strong>${p.name}</strong><small>Custom quote required</small></div><button data-remove="${id}" aria-label="Remove ${p.name}">Remove</button></div>`:''}).join(''):'<p class="empty">Your bag is empty. Choose a piece from the collection to start a conversation.</p>';document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{bag=bag.filter(id=>id!==el.dataset.remove);saveBag();analytics('remove_from_bag',{product_id:el.dataset.remove})})}
document.querySelector('#bag-send').onclick=()=>{if(!bag.length)return;whatsapp(`Hello, I'd like to ask for a quote on: ${bag.map(id=>products.find(p=>p.id===id)?.name).filter(Boolean).join(', ')}. Please contact me about dimensions and customisation.`)};
function defaultStudio(type='sofa',mode='new',productId=null){if(mode==='existing'&&!productId)productId=products[0].id;const p=products.find(x=>x.id===productId);if(p)type=p.kind;const t=types[type]||types.sofa;return {mode,type,productId,size:t.sizes[Math.min(1,t.sizes.length-1)],fabric:'Oxblood',finish:'Natural teak',woodwork:'Clean lines',comfort:'Balanced',chaiseSide:'Right'}}
function openStudio(mode='new',productId=null){const p=products.find(x=>x.id===productId);studio=defaultStudio(p?.kind||'sofa',mode,p?.id||null);document.querySelector('#studio-notes').value='';renderStudio();openPanel(studioDialog);analytics('customizer_open',{mode,product_id:productId||undefined})}
document.querySelectorAll('[data-studio]').forEach(el=>el.onclick=()=>openStudio(el.dataset.studio));
document.querySelectorAll('[data-mode]').forEach(el=>el.onclick=()=>{studio=defaultStudio(el.dataset.mode==='existing'?'sofa':studio.type,el.dataset.mode);renderStudio();analytics('customizer_mode',{mode:studio.mode})});
function group(label,key,options,swatch=false){return `<div class="option-group"><div class="option-title">${label} <span>${String(options.length).padStart(2,'0')} CHOICES</span></div><div class="option-items">${options.map(item=>{const value=typeof item==='string'?item:item.name;const active=studio[key]===value;return `<button type="button" data-option="${key}" data-value="${value}" class="${swatch?'swatch-option ':''}${active?'active':''}" aria-pressed="${active}">${swatch?`<span class="swatch" style="background:${item.color}"></span>`:''}${value}</button>`}).join('')}</div></div>`}
function renderStudio(){document.querySelectorAll('[data-mode]').forEach(el=>el.classList.toggle('active',el.dataset.mode===studio.mode));const p=products.find(x=>x.id===studio.productId);document.querySelector('#studio-context').textContent=studio.mode==='new'?'Choose a form, then set the materials and proportions. We’ll use your choices to start a real design conversation.':`Start with ${p?p.name:'one of our pieces'}, then change what matters to you.`;
 const typeItems=studio.mode==='new'?Object.entries(types).map(([key,val])=>({name:val.name,key})):products.map(item=>({name:item.name,key:item.id}));const typeKey=studio.mode==='new'?studio.type:studio.productId;let typeHtml=`<div class="option-group"><div class="option-title">${studio.mode==='new'?'Choose a piece':'Choose a starting piece'} <span>01 / FORM</span></div><div class="option-items">${typeItems.map(item=>`<button type="button" data-type-choice="${item.key}" class="${typeKey===item.key?'active':''}" aria-pressed="${typeKey===item.key}">${item.name}</button>`).join('')}</div></div>`;
 const t=types[studio.type];let html=typeHtml+group('Size & proportions','size',t.sizes)+(studio.type==='sofa'&&studio.size==='L-shape'?group('Chaise position','chaiseSide',['Left','Right']):'')+(t.fabric?group('Fabric direction','fabric',fabrics,true):'')+group('Teak finish','finish',finishes,true)+group('Woodwork detail','woodwork',woodwork)+(t.comfort?group('Seat feel','comfort',comfort):'');document.querySelector('#studio-options').innerHTML=html;
 document.querySelectorAll('[data-type-choice]').forEach(el=>el.onclick=()=>{const key=el.dataset.typeChoice;if(studio.mode==='new'){studio=defaultStudio(key,'new')}else{const selected=products.find(x=>x.id===key);studio=defaultStudio(selected.kind,'existing',selected.id)}renderStudio();analytics('customizer_choice',{field:'type',value:key})});document.querySelectorAll('[data-option]').forEach(el=>el.onclick=()=>{studio[el.dataset.option]=el.dataset.value;renderStudio();analytics('customizer_choice',{field:el.dataset.option,value:el.dataset.value})});renderPreview()}
let sofaViewerPromise=null,sofaViewerModule=null,previewRequest=0;
function loadSofaViewer(){if(!sofaViewerPromise)sofaViewerPromise=import('./sofa-viewer.js').then(module=>{sofaViewerModule=module;return module}).catch(error=>{sofaViewerPromise=null;throw error});return sofaViewerPromise}
function renderPreview(){const request=++previewRequest;const t=types[studio.type];const img=document.querySelector('#studio-image'),viewer=document.querySelector('#sofa-viewer'),controls=document.querySelector('#viewer-controls'),status=document.querySelector('#preview-status'),note=document.querySelector('.preview-note'),disclaimer=document.querySelector('.preview-disclaimer');const visual=studio.type==='sofa'&&(studio.mode==='new'||studio.productId==='atelier-sofa')&&['2 seater','3 seater','L-shape'].includes(studio.size);const selected=products.find(x=>x.id===studio.productId);const reference=selected?.image||t.image;img.src=reference;img.alt=`Illustrative ${t.name.toLowerCase()} design reference`;document.querySelector('#studio-dock-image').src=reference;viewer.hidden=true;controls.hidden=true;status.hidden=true;img.hidden=false;
 if(visual){img.hidden=true;status.hidden=false;status.textContent='Preparing '+studio.size+' sofa concept…';note.textContent=studio.fabric==='Bring my own'?'A neutral fabric stands in for your own material. The sofa shape and teak finish respond here; bring your fabric to confirm its look.':'Shape, fabric and teak finish respond in this 3D concept. Woodwork and comfort choices are recorded for the workshop quote.';disclaimer.textContent='3D CONCEPT · FINAL DESIGN CONFIRMED BY SHOWROOM';loadSofaViewer().then(module=>{if(request!==previewRequest)return;module.updateSofaPreview({...studio});status.hidden=true;viewer.hidden=false;controls.hidden=false}).catch(()=>{if(request!==previewRequest)return;status.textContent='3D preview unavailable · '+studio.size+' sofa';note.textContent='The 3D preview is unavailable on this device. Your selections are still recorded for the quote.';disclaimer.textContent='PREVIEW UNAVAILABLE · QUOTE DETAILS SAVED'})}
 else{if(studio.type==='sofa'&&studio.size==='Custom size'){img.hidden=true;status.hidden=false;status.textContent='Custom dimensions · workshop drawing required';note.textContent='Include your measurements in the notes. The workshop will prepare an accurate design and quote.';disclaimer.textContent='CUSTOM DESIGN · QUOTE FIRST'}else{note.textContent='This photograph is a design reference. Your selected size, materials and woodwork are recorded for the quote and confirmed by the workshop.';disclaimer.textContent='VISUAL REFERENCE · FINAL DESIGN CONFIRMED BY SHOWROOM'}}
 const p=products.find(x=>x.id===studio.productId);const name=p?.name||`Your ${t.name}`;document.querySelector('#preview-name').textContent=name;document.querySelector('#studio-dock-label').textContent=`${name} · ${studio.size}`;const parts=[studio.size,studio.finish,studio.woodwork];if(studio.type==='sofa'&&studio.size==='L-shape')parts.splice(1,0,studio.chaiseSide+' chaise');if(t.fabric)parts.splice(1,0,studio.fabric);if(t.comfort)parts.push(studio.comfort+' feel');document.querySelector('#preview-chips').innerHTML=parts.map(part=>`<span>${part}</span>`).join('')}
document.querySelector('#viewer-reset').onclick=()=>sofaViewerModule?.resetSofaCamera();document.querySelector('#viewer-save').onclick=()=>{if(sofaViewerModule?.saveSofaView()){analytics('customizer_preview_saved',{type:'sofa',size:studio.size})}};
document.querySelector('#studio-dock').onclick=()=>document.querySelector('#studio-preview').scrollIntoView({behavior:'smooth',block:'start'});
document.querySelector('#studio-send').onclick=()=>{const t=types[studio.type];const p=products.find(x=>x.id===studio.productId);const notes=document.querySelector('#studio-notes').value.trim();const lines=[`Hello, I'd like a quote for ${studio.mode==='existing'&&p?p.name:'a new '+t.name}.`,`Size: ${studio.size}`,`Teak finish: ${studio.finish}`,`Woodwork: ${studio.woodwork}`];if(studio.type==='sofa'&&studio.size==='L-shape')lines.push(`Chaise position: ${studio.chaiseSide}`);if(t.fabric)lines.push(`Fabric direction: ${studio.fabric}`);if(t.comfort)lines.push(`Seat feel: ${studio.comfort}`);if(notes)lines.push(`Other notes: ${notes}`);lines.push('Please contact me to discuss the final design, materials and price.');analytics('customizer_quote',{mode:studio.mode,type:studio.type});whatsapp(lines.join('\n'))};
const information={privacy:{title:'Privacy',body:'This site stores your inquiry bag on your own device. Design choices and notes are passed to WhatsApp only when you choose to send a quote request. They are not saved by this website. Any future analytics should avoid personal information and this notice should be updated before activation.'},terms:{title:'Terms & guarantee',body:'Furniture purchases are described as having a five-year guarantee. Exact coverage, exclusions, care instructions and claim process must be confirmed in written order terms before payment. Product imagery is illustrative. Every custom specification and final price requires showroom confirmation. This prototype does not accept online payment.'},delivery:{title:'Delivery & installation',body:'Delivery areas, charges, timelines, installation responsibilities and return terms depend on the order. Please confirm these in writing with the showroom before placing an order.'}};
document.querySelectorAll('[data-info]').forEach(el=>el.onclick=()=>{const item=information[el.dataset.info];document.querySelector('#info-content').innerHTML=`<span class="kicker">INFORMATION</span><h2 id="info-title">${item.title}</h2><p>${item.body}</p>`;openPanel(infoDialog)});
document.querySelector('#wa-float').onclick=()=>whatsapp("Hello, I'd like to discuss custom furniture for my home.");
document.querySelector('#menu').onclick=e=>{const nav=document.querySelector('#nav');const open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))};document.querySelectorAll('#nav a').forEach(el=>el.onclick=()=>{document.querySelector('#nav').classList.remove('open');document.querySelector('#menu').setAttribute('aria-expanded','false')});
function observeReveals(){if(!('IntersectionObserver'in window))return;const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}},{threshold:.08});document.querySelectorAll('.reveal:not(.visible)').forEach(el=>observer.observe(el))}
document.querySelector('#year').textContent=new Date().getFullYear();saveBag();renderProducts();
